### ISSUE TITLE
Brak dostępu

### ISSUE THREAD

**Issue by Odpluskwiacz** [IT-Club-Lomza/site#1]
fatal: brak dostępu do „https://github.com/IT-Club-Lomza/site.git/”: The requested URL returned error: 403
error 403 oznacza że mój access lvl nie został ustawiony jako write 

![](https://i.stack.imgur.com/BUF4e.png)

https://stackoverflow.com/questions/52533318/how-to-solve-the-requested-url-returned-error-403-in-git-repository
rozwiązanie problemu

**Comment by michigan-musicer** [comment]
running `git remote set-url origin git@github.com:IT-Club-Lomza/site.git` in the repository directory solves this issue. Use SSH over HTTPS to clone the repository where possible.

Reference: https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed
