### ISSUE TITLE
Zmieniałem dzień tygodnia by się zgadzał - wciąż jest po staremu (czwartek o 14:00)

### ISSUE THREAD

**Issue by ArtoszZiomalski** [IT-Club-Lomza/site#14]
W jednym z pull requestów poprawiłem dzień tygodnia, ale wciąż jest po staremu (czwartek o 14:00).

Jeżeli ktoś znajdzie przyczynę przede mną, to proszę opiszcie co zrobiliście.

**Comment by Odpluskwiacz** [comment]
Napiszm mi w '#' który to commit 

Bo w config.toml nic nie zmieniałeś to plik odpowiedzialny za tego typu zadania
